#pragma once

#if defined(_KERNEL_MODE)
#include <devioctl.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#define QNP_WFP_ABI_VERSION 1u
#define QNP_WFP_MAX_PACKET_SIZE 1356u

#define QNP_IOCTL_ACTIVATE CTL_CODE(FILE_DEVICE_NETWORK, 0x900, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define QNP_IOCTL_DEACTIVATE CTL_CODE(FILE_DEVICE_NETWORK, 0x901, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define QNP_IOCTL_READ_PACKET CTL_CODE(FILE_DEVICE_NETWORK, 0x902, METHOD_OUT_DIRECT, FILE_READ_DATA)
#define QNP_IOCTL_INJECT_PACKET CTL_CODE(FILE_DEVICE_NETWORK, 0x903, METHOD_BUFFERED, FILE_WRITE_DATA)

typedef struct QNP_WFP_ACTIVATE_REQUEST_
{
    unsigned long AbiVersion;
    unsigned long ProxyProcessId;
} QNP_WFP_ACTIVATE_REQUEST;

